package gospeak.infra.services.storage.sql.database.tables

import java.time.{Instant, LocalDateTime}

import cats.data.NonEmptyList
import gospeak.core.domain._
import gospeak.core.domain.messages.Message
import gospeak.core.domain.utils.SocialAccounts.SocialAccount._
import gospeak.core.services.meetup.domain.{MeetupEvent, MeetupGroup, MeetupUser, MeetupVenue}
import gospeak.core.services.slack.domain.SlackToken
import gospeak.libs.scala.domain._
import gospeak.libs.sql.dsl.Table._
import gospeak.libs.sql.dsl._

import scala.concurrent.duration.FiniteDuration

/**
 * Generated file, do not update it!
 *
 * Regenerate it using Gospeak CLI (`gospeak.web.GsCLI` class) to keep it in sync with the database state.
 *
 * --
 *
 * Class generated by gospeak.libs.sql.generator.writer.ScalaWriter
 */
class CFPS private(getAlias: Option[String] = Some("c")) extends Table.SqlTable("PUBLIC", "cfps", getAlias) {
  type Self = CFPS

  val ID: SqlField[Cfp.Id, CFPS] = new SqlField[Cfp.Id, CFPS](this, "id") // CHAR(36) NOT NULL
  val GROUP_ID: SqlFieldRef[Group.Id, CFPS, GROUPS] = new SqlFieldRef[Group.Id, CFPS, GROUPS](this, "group_id", GROUPS.table.ID) // CHAR(36) NOT NULL
  val SLUG: SqlField[Cfp.Slug, CFPS] = new SqlField[Cfp.Slug, CFPS](this, "slug") // VARCHAR(120) NOT NULL
  val NAME: SqlField[Cfp.Name, CFPS] = new SqlField[Cfp.Name, CFPS](this, "name") // VARCHAR(120) NOT NULL
  val BEGIN: SqlFieldOpt[LocalDateTime, CFPS] = new SqlFieldOpt[LocalDateTime, CFPS](this, "begin") // TIMESTAMP
  val CLOSE: SqlFieldOpt[LocalDateTime, CFPS] = new SqlFieldOpt[LocalDateTime, CFPS](this, "close") // TIMESTAMP
  val DESCRIPTION: SqlField[Markdown, CFPS] = new SqlField[Markdown, CFPS](this, "description") // VARCHAR(4096) NOT NULL
  val TAGS: SqlField[List[Tag], CFPS] = new SqlField[List[Tag], CFPS](this, "tags") // VARCHAR(150) NOT NULL
  val CREATED_AT: SqlField[Instant, CFPS] = new SqlField[Instant, CFPS](this, "created_at") // TIMESTAMP NOT NULL
  val CREATED_BY: SqlFieldRef[User.Id, CFPS, USERS] = new SqlFieldRef[User.Id, CFPS, USERS](this, "created_by", USERS.table.ID) // CHAR(36) NOT NULL
  val UPDATED_AT: SqlField[Instant, CFPS] = new SqlField[Instant, CFPS](this, "updated_at") // TIMESTAMP NOT NULL
  val UPDATED_BY: SqlFieldRef[User.Id, CFPS, USERS] = new SqlFieldRef[User.Id, CFPS, USERS](this, "updated_by", USERS.table.ID) // CHAR(36) NOT NULL

  override def getFields: List[SqlField[_, CFPS]] = List(ID, GROUP_ID, SLUG, NAME, BEGIN, CLOSE, DESCRIPTION, TAGS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)

  override def getSorts: List[Sort] = List(Sort("date", "date", NonEmptyList.of(CLOSE.desc, NAME.asc)))

  override def searchOn: List[SqlField[_, CFPS]] = List(ID, SLUG, NAME, DESCRIPTION, TAGS)

  override def getFilters: List[Filter] = List()

  def alias(alias: String): CFPS = new CFPS(Some(alias))
}

private[database] object CFPS {
  val table = new CFPS() // table instance, should be accessed through `gospeak.infra.services.storage.sql.database.Tables` object
}
