package gospeak.infra.services.storage.sql.database.tables

import java.time.{Instant, LocalDateTime}

import cats.data.NonEmptyList
import fr.loicknuchel.safeql.Table._
import fr.loicknuchel.safeql._
import gospeak.core.domain._
import gospeak.core.domain.messages.Message
import gospeak.core.domain.utils.SocialAccounts.SocialAccount._
import gospeak.core.services.meetup.domain.{MeetupEvent, MeetupGroup, MeetupUser, MeetupVenue}
import gospeak.core.services.slack.domain.SlackToken
import gospeak.libs.scala.domain._

import scala.concurrent.duration.FiniteDuration

/**
 * Generated file, do not update it!
 *
 * Regenerate it using Gospeak CLI (`gospeak.web.GsCLI` class) to keep it in sync with the database state.
 *
 * --
 *
 * Class generated by fr.loicknuchel.safeql.gen.writer.ScalaWriter
 */
class EXTERNAL_PROPOSALS private(getAlias: Option[String] = Some("ep")) extends Table.SqlTable("PUBLIC", "external_proposals", getAlias) {
  type Self = EXTERNAL_PROPOSALS

  val ID: SqlField[ExternalProposal.Id, EXTERNAL_PROPOSALS] = SqlField(this, "id", "CHAR(36) NOT NULL", JdbcType.Char, nullable = false, 1)
  val TALK_ID: SqlFieldRef[Talk.Id, EXTERNAL_PROPOSALS, TALKS] = SqlField(this, "talk_id", "CHAR(36) NOT NULL", JdbcType.Char, nullable = false, 2, TALKS.table.ID)
  val EVENT_ID: SqlFieldRef[ExternalEvent.Id, EXTERNAL_PROPOSALS, EXTERNAL_EVENTS] = SqlField(this, "event_id", "CHAR(36) NOT NULL", JdbcType.Char, nullable = false, 3, EXTERNAL_EVENTS.table.ID)
  val STATUS: SqlField[Proposal.Status, EXTERNAL_PROPOSALS] = SqlField(this, "status", "VARCHAR(10) NOT NULL", JdbcType.VarChar, nullable = false, 4)
  val TITLE: SqlField[Talk.Title, EXTERNAL_PROPOSALS] = SqlField(this, "title", "VARCHAR(120) NOT NULL", JdbcType.VarChar, nullable = false, 5)
  val DURATION: SqlField[FiniteDuration, EXTERNAL_PROPOSALS] = SqlField(this, "duration", "BIGINT NOT NULL", JdbcType.BigInt, nullable = false, 6)
  val DESCRIPTION: SqlField[Markdown, EXTERNAL_PROPOSALS] = SqlField(this, "description", "VARCHAR(4096) NOT NULL", JdbcType.VarChar, nullable = false, 7)
  val MESSAGE: SqlField[Markdown, EXTERNAL_PROPOSALS] = SqlField(this, "message", "VARCHAR(4096) NOT NULL", JdbcType.VarChar, nullable = false, 8)
  val SPEAKERS: SqlField[NonEmptyList[User.Id], EXTERNAL_PROPOSALS] = SqlField(this, "speakers", "VARCHAR(184) NOT NULL", JdbcType.VarChar, nullable = false, 9)
  val SLIDES: SqlField[Url.Slides, EXTERNAL_PROPOSALS] = SqlField(this, "slides", "VARCHAR(1024)", JdbcType.VarChar, nullable = true, 10)
  val VIDEO: SqlField[Url.Video, EXTERNAL_PROPOSALS] = SqlField(this, "video", "VARCHAR(1024)", JdbcType.VarChar, nullable = true, 11)
  val URL: SqlField[Url, EXTERNAL_PROPOSALS] = SqlField(this, "url", "VARCHAR(1024)", JdbcType.VarChar, nullable = true, 13)
  val TAGS: SqlField[List[Tag], EXTERNAL_PROPOSALS] = SqlField(this, "tags", "VARCHAR(150) NOT NULL", JdbcType.VarChar, nullable = false, 12)
  val CREATED_AT: SqlField[Instant, EXTERNAL_PROPOSALS] = SqlField(this, "created_at", "TIMESTAMP NOT NULL", JdbcType.Timestamp, nullable = false, 14)
  val CREATED_BY: SqlFieldRef[User.Id, EXTERNAL_PROPOSALS, USERS] = SqlField(this, "created_by", "CHAR(36) NOT NULL", JdbcType.Char, nullable = false, 15, USERS.table.ID)
  val UPDATED_AT: SqlField[Instant, EXTERNAL_PROPOSALS] = SqlField(this, "updated_at", "TIMESTAMP NOT NULL", JdbcType.Timestamp, nullable = false, 16)
  val UPDATED_BY: SqlFieldRef[User.Id, EXTERNAL_PROPOSALS, USERS] = SqlField(this, "updated_by", "CHAR(36) NOT NULL", JdbcType.Char, nullable = false, 17, USERS.table.ID)

  override def getFields: List[SqlField[_, EXTERNAL_PROPOSALS]] = List(ID, TALK_ID, EVENT_ID, STATUS, TITLE, DURATION, DESCRIPTION, MESSAGE, SPEAKERS, SLIDES, VIDEO, URL, TAGS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)

  override def getSorts: List[Sort] = List(Sort("title", "title", NonEmptyList.of(TITLE.asc, CREATED_AT.asc)))

  override def searchOn: List[SqlField[_, EXTERNAL_PROPOSALS]] = List(ID, TITLE, STATUS, DESCRIPTION, MESSAGE, TAGS)

  override def getFilters: List[Filter] = List()

  def alias(alias: String): EXTERNAL_PROPOSALS = new EXTERNAL_PROPOSALS(Some(alias))
}

private[database] object EXTERNAL_PROPOSALS {
  val table = new EXTERNAL_PROPOSALS() // table instance, should be accessed through `gospeak.infra.services.storage.sql.database.Tables` object
}
