package gospeak.infra.services.storage.sql.database.tables

import java.time.{Instant, LocalDateTime}

import cats.data.NonEmptyList
import gospeak.core.domain._
import gospeak.core.domain.messages.Message
import gospeak.core.domain.utils.SocialAccounts.SocialAccount._
import gospeak.core.services.meetup.domain.{MeetupEvent, MeetupGroup, MeetupUser, MeetupVenue}
import gospeak.core.services.slack.domain.SlackToken
import gospeak.libs.scala.domain._
import gospeak.libs.sql.dsl.Table._
import gospeak.libs.sql.dsl._

import scala.concurrent.duration.FiniteDuration

/**
 * Generated file, do not update it!
 *
 * Regenerate it using Gospeak CLI (`gospeak.web.GsCLI` class) to keep it in sync with the database state.
 *
 * --
 *
 * Class generated by gospeak.libs.sql.generator.writer.ScalaWriter
 */
class GROUP_MEMBERS private(getAlias: Option[String] = Some("gm")) extends Table.SqlTable("PUBLIC", "group_members", getAlias) {
  type Self = GROUP_MEMBERS

  val GROUP_ID: SqlFieldRef[Group.Id, GROUP_MEMBERS, GROUPS] = new SqlFieldRef[Group.Id, GROUP_MEMBERS, GROUPS](this, "group_id", GROUPS.table.ID) // CHAR(36) NOT NULL
  val USER_ID: SqlFieldRef[User.Id, GROUP_MEMBERS, USERS] = new SqlFieldRef[User.Id, GROUP_MEMBERS, USERS](this, "user_id", USERS.table.ID) // CHAR(36) NOT NULL
  val ROLE: SqlField[String, GROUP_MEMBERS] = new SqlField[String, GROUP_MEMBERS](this, "role") // VARCHAR(10) NOT NULL
  val PRESENTATION: SqlFieldOpt[String, GROUP_MEMBERS] = new SqlFieldOpt[String, GROUP_MEMBERS](this, "presentation") // VARCHAR(4096)
  val JOINED_AT: SqlField[Instant, GROUP_MEMBERS] = new SqlField[Instant, GROUP_MEMBERS](this, "joined_at") // TIMESTAMP NOT NULL
  val LEAVED_AT: SqlFieldOpt[Instant, GROUP_MEMBERS] = new SqlFieldOpt[Instant, GROUP_MEMBERS](this, "leaved_at") // TIMESTAMP

  override def getFields: List[SqlField[_, GROUP_MEMBERS]] = List(GROUP_ID, USER_ID, ROLE, PRESENTATION, JOINED_AT, LEAVED_AT)

  override def getSorts: List[Sort] = List(Sort("joined", "join date", NonEmptyList.of(JOINED_AT.asc)))

  override def searchOn: List[SqlField[_, GROUP_MEMBERS]] = List(ROLE, PRESENTATION)

  override def getFilters: List[Filter] = List()

  def alias(alias: String): GROUP_MEMBERS = new GROUP_MEMBERS(Some(alias))
}

private[database] object GROUP_MEMBERS {
  val table = new GROUP_MEMBERS() // table instance, should be accessed through `gospeak.infra.services.storage.sql.database.Tables` object
}
