/*
 * This file is generated by jOOQ.
 */
package gospeak.libs.sql.testingutils.jooqdb.tables


import gospeak.libs.sql.testingutils.jooqdb.Public
import gospeak.libs.sql.testingutils.jooqdb.tables.records.CategoriesRecord

import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.util.Arrays
import java.util.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl

import scala.Array


object Categories {

  /**
   * The reference instance of <code>PUBLIC.categories</code>
   */
  val CATEGORIES = new Categories
}

/**
 * This class is generated by jOOQ.
 */
class Categories(
  alias : Name,
  child : Table[_ <: Record],
  path : ForeignKey[_ <: Record, CategoriesRecord],
  aliased : Table[CategoriesRecord],
  parameters : Array[ Field[_] ]
)
extends TableImpl[CategoriesRecord](
  alias,
  Public.PUBLIC,
  child,
  path,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table
)
{

  /**
   * The class holding records for this type
   */
  override def getRecordType : Class[CategoriesRecord] = {
    classOf[CategoriesRecord]
  }

  /**
   * The column <code>PUBLIC.categories.id</code>.
   */
  val ID : TableField[CategoriesRecord, Integer] = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>PUBLIC.categories.name</code>.
   */
  val NAME : TableField[CategoriesRecord, String] = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), "")

  /**
   * Create a <code>PUBLIC.categories</code> table reference
   */
  def this() = {
    this(DSL.name("categories"), null, null, null, null)
  }

  /**
   * Create an aliased <code>PUBLIC.categories</code> table reference
   */
  def this(alias : String) = {
    this(DSL.name(alias), null, null, gospeak.libs.sql.testingutils.jooqdb.tables.Categories.CATEGORIES, null)
  }

  /**
   * Create an aliased <code>PUBLIC.categories</code> table reference
   */
  def this(alias : Name) = {
    this(alias, null, null, gospeak.libs.sql.testingutils.jooqdb.tables.Categories.CATEGORIES, null)
  }

  private def this(alias : Name, aliased : Table[CategoriesRecord]) = {
    this(alias, null, null, aliased, null)
  }

  override def getSchema : Schema = Public.PUBLIC

  override def getPrimaryKey : UniqueKey[CategoriesRecord] = {
Internal.createUniqueKey(Categories.CATEGORIES, "CONSTRAINT_4", Array(Categories.CATEGORIES.ID).asInstanceOf[Array[TableField[CategoriesRecord, _] ] ], true)  }

  override def getKeys : List[ UniqueKey[CategoriesRecord] ] = {
    return Arrays.asList[ UniqueKey[CategoriesRecord] ](
        Internal.createUniqueKey(Categories.CATEGORIES, "CONSTRAINT_4", Array(Categories.CATEGORIES.ID).asInstanceOf[Array[TableField[CategoriesRecord, _] ] ], true)
    )
  }

  override def as(alias : String) : Categories = {
    new Categories(DSL.name(alias), this)
  }

  override def as(alias : Name) : Categories = {
    new Categories(alias, this)
  }

  /**
   * Rename this table
   */
  override def rename(name : String) : Categories = {
    new Categories(DSL.name(name), null)
  }

  /**
   * Rename this table
   */
  override def rename(name : Name) : Categories = {
    new Categories(name, null)
  }

  // -------------------------------------------------------------------------
  // Row2 type methods
  // -------------------------------------------------------------------------

  override def fieldsRow : Row2[Integer, String] = {
    super.fieldsRow.asInstanceOf[ Row2[Integer, String] ]
  }
}
