/*
 * This file is generated by jOOQ.
 */
package gospeak.libs.sql.jooqdb


import gospeak.libs.sql.jooqdb.tables.Categories
import gospeak.libs.sql.jooqdb.tables.Kinds
import gospeak.libs.sql.jooqdb.tables.Posts
import gospeak.libs.sql.jooqdb.tables.Users


/**
 * Convenience access to all tables in PUBLIC
 */
object Tables {

  /**
   * The table <code>PUBLIC.categories</code>.
   */
  val CATEGORIES = Categories.CATEGORIES

  /**
   * The table <code>PUBLIC.kinds</code>.
   */
  val KINDS = Kinds.KINDS

  /**
   * The table <code>PUBLIC.posts</code>.
   */
  val POSTS = Posts.POSTS

  /**
   * The table <code>PUBLIC.users</code>.
   */
  val USERS = Users.USERS
}
