/*
 * This file is generated by jOOQ.
 */
package gospeak.libs.sql.testingutils.jooqdb


import org.jooq.impl.CatalogImpl


object DefaultCatalog {

  /**
   * The reference instance of <code>DEFAULT_CATALOG</code>
   */
  val DEFAULT_CATALOG = new DefaultCatalog
}

/**
 * This class is generated by jOOQ.
 */
class DefaultCatalog extends CatalogImpl("") {
}
