/*
 * This file is generated by jOOQ.
 */
package gospeak.libs.sql.testingutils.jooqdb


import gospeak.libs.sql.testingutils.jooqdb.tables.Categories
import gospeak.libs.sql.testingutils.jooqdb.tables.Kinds
import gospeak.libs.sql.testingutils.jooqdb.tables.Posts
import gospeak.libs.sql.testingutils.jooqdb.tables.Users

import java.util.Arrays
import java.util.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


object Public {

  /**
   * The reference instance of <code>PUBLIC</code>
   */
  val PUBLIC = new Public
}

/**
 * This class is generated by jOOQ.
 */
class Public extends SchemaImpl("PUBLIC", DefaultCatalog.DEFAULT_CATALOG) {

  override def getCatalog : Catalog = DefaultCatalog.DEFAULT_CATALOG

  override def getTables : List[Table[_]] = {
    return Arrays.asList[Table[_]](
      Categories.CATEGORIES,
      Kinds.KINDS,
      Posts.POSTS,
      Users.USERS)
  }
}
