/*
 * This file is generated by jOOQ.
 */
package gospeak.libs.sql.jooqdb.tables.records


import gospeak.libs.sql.jooqdb.tables.Users

import java.lang.Integer
import java.lang.String

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class UsersRecord extends UpdatableRecordImpl[UsersRecord](Users.USERS) with Record3[Integer, String, String] {

  /**
   * Setter for <code>PUBLIC.users.id</code>.
   */
  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>PUBLIC.users.id</code>.
   */
  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>PUBLIC.users.name</code>.
   */
  def setName(value : String) : Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>PUBLIC.users.name</code>.
   */
  def getName : String = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>PUBLIC.users.email</code>.
   */
  def setEmail(value : String) : Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>PUBLIC.users.email</code>.
   */
  def getEmail : String = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[String]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row3[Integer, String, String] = {
    super.fieldsRow.asInstanceOf[ Row3[Integer, String, String] ]
  }

  override def valuesRow : Row3[Integer, String, String] = {
    super.valuesRow.asInstanceOf[ Row3[Integer, String, String] ]
  }
  override def field1 : Field[Integer] = Users.USERS.ID
  override def field2 : Field[String] = Users.USERS.NAME
  override def field3 : Field[String] = Users.USERS.EMAIL
  override def component1 : Integer = getId
  override def component2 : String = getName
  override def component3 : String = getEmail
  override def value1 : Integer = getId
  override def value2 : String = getName
  override def value3 : String = getEmail

  override def value1(value : Integer) : UsersRecord = {
    setId(value)
    this
  }

  override def value2(value : String) : UsersRecord = {
    setName(value)
    this
  }

  override def value3(value : String) : UsersRecord = {
    setEmail(value)
    this
  }

  override def values(value1 : Integer, value2 : String, value3 : String) : UsersRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this
  }

  /**
   * Create a detached, initialised UsersRecord
   */
  def this(id : Integer, name : String, email : String) = {
    this()

    set(0, id)
    set(1, name)
    set(2, email)
  }
}
