package gospeak.libs.sql.testingutils.database.tables

import java.time.{Instant, LocalDate}

import gospeak.libs.sql.dsl._

/**
 * Class generated by gospeak.libs.sql.generator.writer.ScalaWriter
 */
class KINDS private() extends Table.SqlTable("PUBLIC", "kinds", None) {
  val CHAR: Field[String, KINDS] = new Field[String, KINDS](this, "char") // CHAR(4)
  val VARCHAR: Field[String, KINDS] = new Field[String, KINDS](this, "varchar") // VARCHAR(50)
  val TIMESTAMP: Field[Instant, KINDS] = new Field[Instant, KINDS](this, "timestamp") // TIMESTAMP
  val DATE: Field[LocalDate, KINDS] = new Field[LocalDate, KINDS](this, "date") // DATE
  val BOOLEAN: Field[Boolean, KINDS] = new Field[Boolean, KINDS](this, "boolean") // BOOLEAN
  val INT: Field[Int, KINDS] = new Field[Int, KINDS](this, "int") // INT
  val BIGINT: Field[Long, KINDS] = new Field[Long, KINDS](this, "bigint") // BIGINT
  val DOUBLE: Field[Double, KINDS] = new Field[Double, KINDS](this, "double") // DOUBLE PRECISION
  val A_LONG_NAME: Field[Int, KINDS] = new Field[Int, KINDS](this, "a_long_name") // INT

  override def getFields: List[Field[_, KINDS]] = List(CHAR, VARCHAR, TIMESTAMP, DATE, BOOLEAN, INT, BIGINT, DOUBLE, A_LONG_NAME)
}

private[database] object KINDS {
  val table = new KINDS() // unique table instance, should be accessed through `gospeak.libs.sql.testingutils.database.Tables` object
}
