package gospeak.infra.services.storage.sql.database

import fr.loicknuchel.safeql.Table.SqlTable

/**
 * Generated file, do not update it!
 *
 * Regenerate it using Gospeak CLI (`gospeak.web.GsCLI` class) to keep it in sync with the database state.
 *
 * --
 *
 * Class generated by fr.loicknuchel.safeql.gen.writer.ScalaWriter
 */
object Tables {
  val CFPS: tables.CFPS = tables.CFPS.table
  val COMMENTS: tables.COMMENTS = tables.COMMENTS.table
  val CONTACTS: tables.CONTACTS = tables.CONTACTS.table
  val CREDENTIALS: tables.CREDENTIALS = tables.CREDENTIALS.table
  val EVENT_RSVPS: tables.EVENT_RSVPS = tables.EVENT_RSVPS.table
  val EVENTS: tables.EVENTS = tables.EVENTS.table
  val EXTERNAL_CFPS: tables.EXTERNAL_CFPS = tables.EXTERNAL_CFPS.table
  val EXTERNAL_EVENTS: tables.EXTERNAL_EVENTS = tables.EXTERNAL_EVENTS.table
  val EXTERNAL_PROPOSALS: tables.EXTERNAL_PROPOSALS = tables.EXTERNAL_PROPOSALS.table
  val GROUP_MEMBERS: tables.GROUP_MEMBERS = tables.GROUP_MEMBERS.table
  val GROUP_SETTINGS: tables.GROUP_SETTINGS = tables.GROUP_SETTINGS.table
  val GROUPS: tables.GROUPS = tables.GROUPS.table
  val LOGINS: tables.LOGINS = tables.LOGINS.table
  val PARTNERS: tables.PARTNERS = tables.PARTNERS.table
  val PROPOSAL_RATINGS: tables.PROPOSAL_RATINGS = tables.PROPOSAL_RATINGS.table
  val PROPOSALS: tables.PROPOSALS = tables.PROPOSALS.table
  val SPONSOR_PACKS: tables.SPONSOR_PACKS = tables.SPONSOR_PACKS.table
  val SPONSORS: tables.SPONSORS = tables.SPONSORS.table
  val TALKS: tables.TALKS = tables.TALKS.table
  val USER_REQUESTS: tables.USER_REQUESTS = tables.USER_REQUESTS.table
  val USERS: tables.USERS = tables.USERS.table
  val VENUES: tables.VENUES = tables.VENUES.table
  val VIDEO_SOURCES: tables.VIDEO_SOURCES = tables.VIDEO_SOURCES.table
  val VIDEOS: tables.VIDEOS = tables.VIDEOS.table

  def getTables: List[SqlTable] = List(CFPS, COMMENTS, CONTACTS, CREDENTIALS, EVENT_RSVPS, EVENTS, EXTERNAL_CFPS, EXTERNAL_EVENTS, EXTERNAL_PROPOSALS, GROUP_MEMBERS, GROUP_SETTINGS, GROUPS, LOGINS, PARTNERS, PROPOSAL_RATINGS, PROPOSALS, SPONSOR_PACKS, SPONSORS, TALKS, USER_REQUESTS, USERS, VENUES, VIDEO_SOURCES, VIDEOS)
}
